# Generated by Django 2.2.6 on 2020-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200809_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books', through='p_library.Reading', to='p_library.Book', verbose_name='Читает'),
        ),
    ]
