# Generated by Django 2.2.6 on 2020-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200809_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='book_covers', verbose_name='Обложка книги'),
        ),
    ]
