# Generated by Django 2.2.6 on 2020-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='book_covers/%Y/%m/%d', verbose_name='Обложка книги'),
        ),
    ]
